package school.faang.user_service.exception.recommendation;

public class RequestErrorMessage {
    public static final String RECOMMENDATION_REQUEST_MESSAGE = "THE MESSAGE OF THE RECOMMENDATION REQUEST CANNOT BE EMPTY";
    public static final String RECOMMENDATION_REQUEST_RECEIVER = "THE RECEIVER OF THE RECOMMENDATION REQUEST IS NOT SPECIFIED";
    public static final String RECOMMENDATION_REQUEST_REQUESTER = "THE REQUESTER OF THE RECOMMENDATION REQUEST IS NOT SPECIFIED";
}
