name: CI Pipeline

on:
  pull_request:
    branches:
      - Titan-master-stream7

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Checkstyle on changed files
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Build and run tests
        run: ./gradlew test

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
